### ISSUE TITLE
Use the right zero default for vega-lite

### ISSUE THREAD

**Issue by domoritz** [uwdata/draco#75]
Vega-lite adds zero by default for quantitative, non-binned scales.

**Comment by Mestway** [comment]
So it means the following, right?

* Translating from ASP to Vega-lite: if there is no zero specified and quantitative and non-binned, we would add `zero=False` since ASP's default is that zero is False when unspecified.

* Translating from Vega-lite to ASP: if no zero is specified and quantitative and non-binned, we would add `zero(e)` since Vega-lite spec indicates that zero is true.

* Translating from CQL to ASP: if no zero is specified and quantitative and non-binned, we would do nothing, since it is time for ASP to figure out.

**Comment by domoritz** [comment]
Yes, exactly. 

The completely correct logic is in https://github.com/vega/vega-lite/blob/59be8100e2a35a442c07bf7d0d4b68b710a1da9e/src/compile/scale/properties.ts#L217. Since we are in JavaScript, we can even call this function.

**Comment by Mestway** [comment]
Resolved both here and in js.
